/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Rupert' at '03/03/16 12:31' with Gradle 2.11
 *
 * @author Rupert, @date 03/03/16 12:31
 */
public class Library {
    public boolean someLibraryMethod() {
        return false;
    }
}
