import instruments.AUDUSD;

import org.junit.Test;

import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'Rupert' at '03/03/16 12:31' with Gradle 2.11
 *
 * @author Rupert, @date 03/03/16 12:31
 */

public class InstrumentTest {
    @Test public void testInstrument() {
        AUDUSD classToTest = new AUDUSD();
        assertSame("Error, mid price is wrong", 0.72, classToTest.mid);
    }
    
    @Test
    public void testAssertNotNull() {
      assertNotNull("should not be null", new AUDUSD());
    }
}
