import java.math.BigDecimal;
import java.math.RoundingMode;

import instruments.AUDUSD;
import instruments.EURGBP;
import instruments.EURJPY;
import instruments.EURUSD;
import instruments.GBPUSD;
import instruments.USDJPY;
import instruments.AUDUSD.Spreads;

import org.junit.Test;

import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'Rupert' at '03/03/16 12:31' with Gradle 2.11
 *
 * @author Rupert, @date 03/03/16 12:31
 */

public class InstrumentTest {
    @Test 
    public void testAUDUSDMid() {
    	BigDecimal mid = BigDecimal.valueOf(0.72);
        assertEquals("Error, mid price is wrong", mid, AUDUSD.mid);
    }
    
    @Test 
    public void testAUDUSDSpread() {
    	BigDecimal spread = new BigDecimal(0.00030).setScale(5, RoundingMode.HALF_UP);

        assertEquals("Spread has changed", spread, Spreads.band1offer.getSpread());
    }
    
    @Test
    public void testAssertNotNull() {
      assertNotNull("should not be null", new AUDUSD());
      assertNotNull("should not be null", new EURGBP());
      assertNotNull("should not be null", new EURJPY());
      assertNotNull("should not be null", new EURUSD());
      assertNotNull("should not be null", new GBPUSD());
      assertNotNull("should not be null", new USDJPY());
    }
}
