import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'Rupert' at '03/03/16 12:31' with Gradle 2.11
 *
 * @author Rupert, @date 03/03/16 12:31
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classToTest = new Library();
        assertFalse("someLibraryMethod should return 'false'", classToTest.someLibraryMethod());
    }
}
