import org.junit.Test;

import simulator.MarketData;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'Rupert' at '03/03/16 12:31' with Gradle 2.11
 *
 * @author Rupert, @date 03/03/16 12:31
 */

public class MarketDataTest {
    @Test 
    public void testMarketData() {
        MarketData classToTest = new MarketData();
        assertTrue("Error, random is too high", 25 >= classToTest.move);
        assertTrue("Error, random is too low",  -25  <= classToTest.move);
    }
    
    @Test
    public void testAssertNotNull() {
      assertNotNull("should not be null", new MarketData());
    }
}
