import org.junit.Test;

import simulator.MarketData;
import simulator.Venue;
import venues.Ebs;
import venues.Fxall;
import venues.Hotspot;
import venues.Lava;
import venues.Reuters;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'Rupert' at '03/03/16 12:31' with Gradle 2.11
 *
 * @author Rupert, @date 03/03/16 12:31
 */

public class VenueTest {
	
	@Test
    public void testVenue() {
		Venue v = new Venue();
		MarketData m = v.MarketDataUpdate("EURUSD", "EBS");
	
	    assertNotNull("should not be null", m.bids);
	    assertNotNull("should not be null", m.offers);	    
	}
	
    @Test
    public void testAssertNotNull() {
      assertNotNull("should not be null", new Ebs());
      assertNotNull("should not be null", new Fxall());
      assertNotNull("should not be null", new Hotspot());
      assertNotNull("should not be null", new Lava());
      assertNotNull("should not be null", new Reuters());
    }
}
