import java.math.BigDecimal;
import java.math.RoundingMode;

import org.junit.Test;

import pricer.VWAP;
import simulator.MarketData;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'Rupert' at '03/03/16 12:31' with Gradle 2.11
 *
 * @author Rupert, @date 03/03/16 12:31
 */

public class VWAPTest {
	
    @Test 
    public void testVWAP() {
    	
    	BigDecimal bid1 = new BigDecimal(1.09);
    	BigDecimal bid2 = new BigDecimal(1.089);
    	BigDecimal bid3 = new BigDecimal(1.088);
    	BigDecimal bid4 = new BigDecimal(1.087);
    	BigDecimal bid5 = new BigDecimal(1.086);
    	
    	BigDecimal offer1 = new BigDecimal(1.09);
    	BigDecimal offer2 = new BigDecimal(1.091);
    	BigDecimal offer3 = new BigDecimal(1.092);
    	BigDecimal offer4 = new BigDecimal(1.093);
    	BigDecimal offer5 = new BigDecimal(1.094);
       
    	BigDecimal[] bids = new BigDecimal[] { bid1, bid2, bid3, bid4, bid5 };
    	BigDecimal[] offers = new BigDecimal[] { offer1, offer2, offer3, offer4, offer5 };
    			
    	MarketData m = new MarketData("EURUSD", 1000000, bids, offers);
       
    	VWAP v = new VWAP(m);
    	
    	BigDecimal bid = new BigDecimal(1.08679).setScale(5, RoundingMode.HALF_UP);
    	BigDecimal offer = new BigDecimal(1.09321).setScale(5, RoundingMode.HALF_UP);    	
    	
    	assertEquals("Error, VWAP bid is wrong", bid, v.bid);
    	assertEquals("Error, VWAP offer is wrong", offer, v.offer);
    }
}
